package pageobjects;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ContactUs {

    private WebDriver driver;

    @FindBy(id="name")
    private WebElement nombreCompleto;
    @FindBy(id="email")
    private WebElement emailCompleto;
    @FindBy(id="input#phone")
    private WebElement telefonoCompleto;
    @FindBy(id="metodocontacto")
    private WebElement contactoCompleto;
    @FindBy(id="comments")
    private WebElement textoCompleto;
    @FindBy(id="acepto-la-politica-de-proteccion-de-datos")
    private WebElement bb;
    @FindBy(id="cta w-100")
    private WebElement botonCompleto;
    @FindBy(id="//div[contains(@id, 'subtitulo-hero')]")
    private WebElement container;

    public ContactUs(WebDriver driver){

        this.driver = driver;
        PageFactory.initElements(driver, this);
    }

    public void writeNombreCompleto(String nombrecito){
        nombreCompleto.sendKeys(nombrecito);
    }

    public void writeEmailCompleto(String emailNuevo){
        emailCompleto.sendKeys(emailNuevo);;
    }

    public void writePhoneCompleto(String telefono){
        telefonoCompleto.sendKeys(telefono);
    }

    public void writeContactoCompleto(String cont){
        Select selectWeb = new Select(contactoCompleto);
        selectWeb.selectByVisibleText(cont);
    }

    public void writeMessage(String mensaje){
        textoCompleto.sendKeys(mensaje);
    }

    public void writeBoton(){
        bb.click();
    }

    public void sendContact(){
        botonCompleto.click();
    }
}
