// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import pageobjects.ContactUs;

import java.util.*;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class SearhiphoneTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\ogonzama\\OneDrive - NTT DATA EMEAL\\Documents\\Testing\\Pruebas\\selenium-export\\src\\test\\resources\\chromedriver.exe");

        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void searhiphone() {
        driver.get("https://www.mercadolibre.com.co/");
        driver.manage().window().setSize(new Dimension(1296, 696));
        {
            WebElement element = driver.findElement(By.id(":R1j7a9q:"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("cb1-edit")).click();
        driver.findElement(By.id("cb1-edit")).sendKeys("iphone");
        driver.findElement(By.id("cb1-edit")).sendKeys(Keys.ENTER);
        driver.findElement(By.xpath("//div[@id=\':Rakloq:\']/div[2]/div[2]/a/h2")).click();
        driver.findElement(By.linkText("Apple iPhone 13 (128 GB) - Azul - Distribuidor autorizado")).click();
        driver.findElement(By.cssSelector("#\\3AR15d7a6c4um\\3A > .andes-button__content")).click();
    }

    @Test
    public void navigateToColombia(){
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\ogonzama\\OneDrive - NTT DATA EMEAL\\Documents\\Testing\\Pruebas\\selenium-export\\src\\test\\resources\\chromedriver.exe");

        WebDriver driver = new ChromeDriver();

        driver.get("https://mercadolibre.com");

        driver.findElement(By.xpath("//nav/ul/li/a[contains(text(), 'Colombia')]")).click();

        String currentUrl = driver.getCurrentUrl();

        assertTrue(currentUrl.contains("https://www.mercadolibre.com.co/#from=homecom"));

        driver.quit();
    }

    @Test
    public void workWithSelects() throws InterruptedException {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\ogonzama\\OneDrive - NTT DATA EMEAL\\Documents\\Testing\\Pruebas\\selenium-export\\src\\test\\resources\\chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.get("https://pointerdigital.es/contacto.html?gclid=EAIaIQobChMImY-hyv2ihQMVhIlQBh33PQQpEAAYASAAEgKc7_D_BwE");

        WebElement select = driver.findElement(By.id("metodocontacto"));
        Select selectWeb = new Select(select);
        selectWeb.selectByIndex(1);
        Thread.sleep(2000);
        selectWeb.selectByIndex(2);
        Thread.sleep(2000);
        selectWeb.selectByIndex(0);
        Thread.sleep(2000);

        selectWeb.selectByVisibleText("Webmaster");
        Thread.sleep(2000);

        selectWeb.selectByValue("llamada-mananas");
        Thread.sleep(2000);

        driver.quit();
    }

    @Test
    public void sendContactUs() throws InterruptedException {
        driver.get("https://pointerdigital.es/contacto.html?gclid=EAIaIQobChMImY-hyv2ihQMVhIlQBh33PQQpEAAYASAAEgKc7_D_BwE");

        ContactUs contactUs = new ContactUs(driver);

        contactUs.writeNombreCompleto("Óscar González");
        contactUs.writeEmailCompleto("oscargonmar09@gmail.com");
        contactUs.writePhoneCompleto("611611611");
        contactUs.writeContactoCompleto("Mejor por email");
        contactUs.writeMessage("De la mejor manera posible");
        contactUs.writeBoton();
        contactUs.sendContact();

        driver.quit();

    }

    @Test
    public void prueba(){
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\ogonzama\\OneDrive - NTT DATA EMEAL\\Documents\\Testing\\Pruebas\\selenium-export\\src\\test\\resources\\chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.get("https://pointerdigital.es/contacto.html?gclid=EAIaIQobChMImY-hyv2ihQMVhIlQBh33PQQpEAAYASAAEgKc7_D_BwE");

        driver.findElement(By.id("name")).sendKeys("pruebecita");

        driver.quit();
    }

    @Test
    public void santaluciaPrueba(){
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\ogonzama\\OneDrive - NTT DATA EMEAL\\Documents\\Testing\\Pruebas\\selenium-export\\src\\test\\resources\\chromedriver.exe");

        WebDriver driver = new ChromeDriver();

        driver.get("https://cscvfun.santalucia.es/vida/insurance-data");
        driver.manage().window().maximize();

        driver.findElement(By.xpath("//button[@id='onetrust-accept-btn-handler']")).click();

        driver.findElement(By.xpath("//input[@id='fechanacimiento']")).sendKeys("12/07/1988");

        driver.quit();
    }

    @Test
    public void getElementsTest(){
        driver.get("https://www.mercadolibre.com.co/");
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(10L, TimeUnit.SECONDS);

        WebElement searchbox = driver.findElement(By.id("cb1-edit"));
        searchbox.sendKeys("guitarra electrica");
        searchbox.sendKeys(Keys.ENTER);

        List<WebElement> results = driver.findElements(By.cssSelector("ol[class*='ui-search-layout'] li"));
        System.out.println("el numero es: " + results.size());

        By priceBy = By.cssSelector("div[class*='ui-search-price--size-medium'] span[class='price-tag-text-sr-only']");
        By nameBy = By.cssSelector("h2");

        for(WebElement result: results){
            System.out.println("_________");
            System.out.println("el precio es: " + result.findElement(priceBy).getText());
            System.out.println("el precio es: " + result.findElement(nameBy).getText());
            System.out.println("_________");
        }
    }
}
